# Generated by Django 5.1.15 on 2026-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskimage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskimage',
            name='status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='taskimage',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
