# Generated by Django 5.1.15 on 2026-05-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_taskimage_error_message_taskimage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
